/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InscritRouteImport } from './routes/inscrit'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const InscritRoute = InscritRouteImport.update({
  id: '/inscrit',
  path: '/inscrit',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avis': typeof AvisRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/inscrit': typeof InscritRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avis': typeof AvisRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/inscrit': typeof InscritRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avis': typeof AvisRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/inscrit': typeof InscritRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avis'
    | '/connexion'
    | '/dashboard'
    | '/inscription'
    | '/inscrit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/avis'
    | '/connexion'
    | '/dashboard'
    | '/inscription'
    | '/inscrit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avis'
    | '/connexion'
    | '/dashboard'
    | '/inscription'
    | '/inscrit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AvisRoute: typeof AvisRoute
  ConnexionRoute: typeof ConnexionRoute
  DashboardRoute: typeof DashboardRoute
  InscriptionRoute: typeof InscriptionRoute
  InscritRoute: typeof InscritRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inscrit': {
      id: '/inscrit'
      path: '/inscrit'
      fullPath: '/inscrit'
      preLoaderRoute: typeof InscritRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AvisRoute: AvisRoute,
  ConnexionRoute: ConnexionRoute,
  DashboardRoute: DashboardRoute,
  InscriptionRoute: InscriptionRoute,
  InscritRoute: InscritRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
