/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfRouteImport } from './routes/prof'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PaiementRouteImport } from './routes/paiement'
import { Route as InscritRouteImport } from './routes/inscrit'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ProfRoute = ProfRouteImport.update({
  id: '/prof',
  path: '/prof',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementRoute = PaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const InscritRoute = InscritRouteImport.update({
  id: '/inscrit',
  path: '/inscrit',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avis': typeof AvisRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/inscrit': typeof InscritRoute
  '/paiement': typeof PaiementRoute
  '/presentation': typeof PresentationRoute
  '/prof': typeof ProfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avis': typeof AvisRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/inscrit': typeof InscritRoute
  '/paiement': typeof PaiementRoute
  '/presentation': typeof PresentationRoute
  '/prof': typeof ProfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avis': typeof AvisRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/inscrit': typeof InscritRoute
  '/paiement': typeof PaiementRoute
  '/presentation': typeof PresentationRoute
  '/prof': typeof ProfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avis'
    | '/connexion'
    | '/dashboard'
    | '/inscription'
    | '/inscrit'
    | '/paiement'
    | '/presentation'
    | '/prof'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/avis'
    | '/connexion'
    | '/dashboard'
    | '/inscription'
    | '/inscrit'
    | '/paiement'
    | '/presentation'
    | '/prof'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avis'
    | '/connexion'
    | '/dashboard'
    | '/inscription'
    | '/inscrit'
    | '/paiement'
    | '/presentation'
    | '/prof'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AvisRoute: typeof AvisRoute
  ConnexionRoute: typeof ConnexionRoute
  DashboardRoute: typeof DashboardRoute
  InscriptionRoute: typeof InscriptionRoute
  InscritRoute: typeof InscritRoute
  PaiementRoute: typeof PaiementRoute
  PresentationRoute: typeof PresentationRoute
  ProfRoute: typeof ProfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prof': {
      id: '/prof'
      path: '/prof'
      fullPath: '/prof'
      preLoaderRoute: typeof ProfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement': {
      id: '/paiement'
      path: '/paiement'
      fullPath: '/paiement'
      preLoaderRoute: typeof PaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscrit': {
      id: '/inscrit'
      path: '/inscrit'
      fullPath: '/inscrit'
      preLoaderRoute: typeof InscritRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AvisRoute: AvisRoute,
  ConnexionRoute: ConnexionRoute,
  DashboardRoute: DashboardRoute,
  InscriptionRoute: InscriptionRoute,
  InscritRoute: InscritRoute,
  PaiementRoute: PaiementRoute,
  PresentationRoute: PresentationRoute,
  ProfRoute: ProfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
